version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: monthly
      time: "15:45"
  # Maintian npm dependencies
  - package-ecosystem: npm
    directory: "/"
    ignore:
      - dependency-name: electron
    commit-message:
      prefix: chore
      include: scope
    schedule:
      interval: monthly
      time: "16:00"
    open-pull-requests-limit: 10
