language: node_js

node_js: "6"

addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus

before_install:
  - cd linux/
  - npm i -g npm@5.2.0

script:
  - npm run build
  - npm run test

git:
  depth: 1

cache:
  directories:
  - linux/node_modules

deploy:
  - provider: releases
    skip_cleanup: true
    file_glob: true
    api_key: $GITHUB_TOKEN
    file: build/installers/*
    on:
      tags: true
