language: node_js

node_js: "6"

os:
  - linux
  - osx

git:
  depth: 1

addons:
  apt:
    packages:
    - fakeroot
    - dpkg
    - rpm
    - lintian
    - libdbus-1-dev
    - libglib2.0-dev
    - reprepro
    - createrepo

before_install:
- npm i -g npm@5.6.0

install:
- npm install
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run darwin; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run linux; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run windows; fi

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    export DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint linux; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run lint shared; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd linux; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run lint darwin; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd darwin; fi
- npm run test

before_cache:
- cd ..

cache:
  directories:
  - node_modules
  - darwin/node_modules
  - linux/node_modules
  - windows/node_modules

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" && -n "$TRAVIS_TAG" ]]; then
    cd linux;
    openssl aes-256-cbc -K $encrypted_6866d25ad40b_key -iv $encrypted_6866d25ad40b_iv -in sig/headset_priv.asc.enc -out headset_priv.asc -d;
    npm run repo;
    cd ..;
  fi

deploy:
- provider: releases
  skip_cleanup: true
  file_glob: true
  api_key: "$GITHUB_TOKEN"
  file:
    - linux/build/installers/*
    - darwin/build/installers/*.dmg
    - darwin/build/installers/*.zip
  name: $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  draft: true
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  local_dir: linux/gh-pages
  github_token: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
env:
  global:
    secure: nRtG4v+jNQbCQg/qhYwrPaBMuwGxG8z2+kfiV86dOzNy9+th5UTvcFWYFj05J024CBlqNuc6aykCQ3aBIngAWw5NMl9coAfcBh1z64FXZO4KPjk2rPJIm8E2v/wpISjB0GZOf4Vr6rHBrggXGjkDX+YGF4bd+xCylS6K1hVKbvGlnYf1HBx6ewWp9zqkqyYyB9Vif7AGe/dH5jTzqPNYtt+q4fffxlFTEMvz0L/60szlWFrCfMKLAjA/YY24FvWBExJZ/SqFqugHS9zlhwlLbCoN/sKBG7JlJJIlQvGUxX5upgJI1QJ/RMWLWg+6gkUgk2xNhBMNWF1Ys8kvzBLFLhWrVOH7QknwObJkc3SJkMz5J/rIkt1VrwG0vAymiVUAfSLGTwvuwoMfA8tkAF7zQtMwWUwU5E2CDfh0grPBF/VPQGCKX2VO425Yuw/S2FokeV7bDRyQP3yPnusSZlTX45XyE8EkssK7j+lOZnl0bjbENZJEH0qlh2orRsC/xihBpo4M49G/Xae3lAlDBp9si7tzRCoyTo4v2KzW/r5rdmrqrfgrSFugpLYJpQsUZVM7d2vU9sJB5TTQ2tZuEAB8UAQprgNQF7IS1xkPafq321KYv21YQbPiqi6nBIzRzDbEEbl4qavS9MnfXgAC4z+RYQiv3XM6FRABsHJhwiK7UuE=
