version: "{build}"

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

image: Visual Studio 2017

clone_depth: 1

environment:
  nodejs_version: "12"
  CERT_PASSWORD:
    secure: BOXjWrY24hdw8EhsmLkP5RVxG/aY/16gnAt//DlVIHOadhfJWHgQfh+qI7oUkgP2

platform:
  - x86

cache:
  - '%APPDATA%\npm-cache'

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - npm ci

before_build:
  - npm run lint

build_script:
  - npm run pack:windows
  - npm run dist:windows 2> $null
  - npm run choco

test_script:
  - npm run test:app

artifacts:
  - path: build\installers\headset-*-setup.exe
    name: HeadsetApp
  - path: build\installers\headset-*-full.nupkg
    name: HeadsetNupkg
  - path: build\installers\RELEASES
    name: HeadsetReleases
  - path: build\headset.*.nupkg
    name: HeadsetChoco

deploy:
  - provider: GitHub
    artifact: HeadsetApp, HeadsetNupkg, HeadsetReleases
    auth_token: $(GITHUB_TOKEN)
    draft: true
    description: ''
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    server: https://push.chocolatey.org/
    artifact: HeadsetChoco
    skip_symbols: true
    api_key: $(CHOCO_TOKEN)
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: npn0SEwIlCoQgqThPkawpHuj551XN5gtIBuH+fEGEsCM0WW9lNOCUsgOxrSch1GOzEnnVWSbWreH/ZSlOXYhvS7bPz32djVyAf+jZ5u/qxw=
    channel: '#travis-ci'
