name: CI
env:
  node-version: 14

on:
  push:
    branches: [ main ]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    outputs:
      current_tag: ${{ steps.tags.outputs.newtag }}
      previous_tag: ${{ steps.tags.outputs.oldtag }}

    steps:
    - name: Get npm cache directory
      id: npm-cache-dir
      run: echo "::set-output name=dir::$(npm config get cache)"
    - name: Set up npm cache
      uses: actions/cache@v2.1.4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ env.node-version }}
    - name: Update npm
      run: npm install -g npm@latest
    - name: Install Dependencies (Linux)
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt-get install fakeroot dpkg rpm lintian gnupg2 xvfb
    - name: Install Dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install graphicsmagick imagemagick
    - name: Fix git checkout line endings
      run: git config --global core.autocrlf input
    - name: Get source
      uses: actions/checkout@v2
    - name: Get tags
      id: tags
      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-18.04'
      run: |
        git fetch --tags -f
        ./bin/getTags.sh
    - name: Install npm dependencies
      run: npm ci
    - name: Linting
      run: npm run lint

    - name: Building (Linux)
      if: matrix.os == 'ubuntu-18.04'
      run: npm run build:linux
    - name: Building (macOS)
      if: matrix.os == 'macos-latest'
      run: npm run build:darwin
      env:
        CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
    - name: Building (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run build:windows
      env:
        CERT_PASSWORD: ${{ secrets.WINDOWS_CERT_PASSWORD }}
    - name: Signing RedHat installer
      if: matrix.os == 'ubuntu-18.04' && startsWith(github.ref, 'refs/tags/')
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.LINUX_CERT_PASSWORD }} --output headset_priv.asc sig/headset_priv.asc.gpg
        npm run sign:redhat

    - name: Testing app
      uses: GabrielBB/xvfb-action@v1.5
      with:
        run: npm run test:app
    - name: Test Linux installers
      if: matrix.os == 'ubuntu-18.04'
      run: npm run test:linux

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: installers-${{ matrix.os }}
        path: build/installers/*

  publish:
    name: Publish to Github Releases
    needs: build
    runs-on: 'ubuntu-18.04'
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - run: mkdir -p build/installers
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: build/installers/
    # Artifacts are downloaded to their own sub-directory, we need to move them
    - name: Move artifacts from their subdirectories
      working-directory: build/installers/
      run: |
        find . -type f -exec mv {} . \;
        find . -type d -delete
    - name: Create a release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: build/installers/*
        body: https://github.com/headsetapp/headset-electron/compare/v${{ needs.build.outputs.previous_tag }}...v${{ needs.build.outputs.current_tag }}
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}

  linux_repo:
    name: Publish Linux repositories
    needs: build
    runs-on: 'ubuntu-18.04'
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Install Dependencies
      run: sudo apt-get install reprepro createrepo
    - name: Get source
      uses: actions/checkout@v2
    - run: mkdir -p build/installers
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: installers-ubuntu-18.04
        path: build/installers/
    - name: Creating repositories
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.LINUX_CERT_PASSWORD }} --output headset_priv.asc sig/headset_priv.asc.gpg
        npm run repo
    - name: Deploy Linux repositories
      uses: crazy-max/ghaction-github-pages@v2.3.0
      with:
        build_dir: gh-pages
        commit_message: Deploy ${{ needs.build.outputs.current_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chocolatey:
    name: Publish to Chocolatey
    needs: build
    runs-on: 'windows-latest'
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'headsetapp/headset-electron'
    steps:
    - name: Get source
      uses: actions/checkout@v2
    - run: mkdir -p build/installers
    - name: Fix git checkout line endings
      run: git config --global core.autocrlf input
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: installers-windows-latest
        path: build/installers/
    - name: Creating nuspec
      run: npm run choco
    - name: Publishing
      working-directory: ./build
      run: choco push -s "https://push.chocolatey.org/" -k ${{ secrets.CHOCO_TOKEN }}

  homebrew:
    name: Publish to Homebrew cask
    needs: [build, publish]
    runs-on: 'macos-latest'
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'headsetapp/headset-electron'
    steps:
    - name: Delete credentials
      run: printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
    - name: Bump the Homebrew cask
      run: brew bump-cask-pr --no-browse --verbose --version="${{ needs.build.outputs.current_tag }}" headset
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW }}
